### ISSUE TITLE
[Obtain Subset of CLOTH4D]  Error

### ISSUE THREAD

**Issue by 2InfinityN6eyond** [AemikaChow/CLOTH4D#5]
Hello? 

Thank you for your fascinating work!

While reading Paper, I was amused about the data collection process.

I would really like to download subset of data, but it seems now the link is not valid anymore..

**Comment by AemikaChow** [comment]
Thanks for your interest in our work and I am sorry that the original files were deleted in early of July due to our new storage capacity limitation policy. I have re-uploaded these files but found that some of them are corrupted. Please find parts 3, 4, and 5 in the updated link. I will upload the remaining two parts before the end of this week.

**Comment by 2InfinityN6eyond** [comment]
Wow, thank you for your immediate reply.
Now I can download the files!
I would like to express my gratitute for this work, which has made my research  possible.

I hope your research goes well.
